package template

const NotEditMark = `
// Code generated by fitan/gen. DO NOT EDIT.
// Code generated by fitan/gen. DO NOT EDIT.
// Code generated by fitan/gen. DO NOT EDIT.
`

const Header = NotEditMark + `
package {{.Package}}

import(
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/schema"
	"gorm.io/gorm/clause"

	"fitan/gen"
	"fitan/gen/field"
	"fitan/gen/helper"
	{{ if .StructPkgPath  }}"{{.StructPkgPath}}"{{ end }}
)
`

const UnitTestHeader = NotEditMark + `
package {{.}}

import(
	"context"
	"fmt"
	"strconv"
	"testing"

	"gorm.io/driver/sqlite"
	"gorm.io/gorm"
)

`
